---
- name: Install clementine
  pacman: name=clementine state=present
  tags:
    - clementine

- name: Install cheese
  pacman: name=cheese state=present
  tags:
    - cheese

- name: Download Franz
  become: yes
  get_url:
    url: https://github.com/meetfranz/franz/releases/download/v5.1.0/franz-5.1.0-x86_64.AppImage
    dest: /tmp/franz-installer.Appimage
    mode: 0755
    force: yes
  tags:
    - franz

- name: Install Franz
  shell: /tmp/franz-installer.Appimage
  tags:
    - franz

- name: Install imagemagick and dependencies
  pacman:
    state: present
    name:
      - libraw
      - libpng
      - librsvg
      - openjpeg2
      - imagemagick
  tags:
    - imagemagick

- name: Install GIMP
  pacman:
    state: present
    name:
      - gimp
      - gimp-plugin-gmic
  tags:
    - gimp

- name: Install Okular
  pacman:
    name: okular
    state: present

- name: Install vlc
  pacman:
    state: present
    name:
      - vlc
