---
- name: Install python
  pacman:
    state: present
    name:
      - ipython
      - python-pip

- name: Install global python requirements
  pip: name={{item}} state=present
  with_items:
    - asyncio
    - numpy
    - pylint
    - sanic
