---
- name: Install docker
  pacman:
    state: present
    name:
      - docker
      - docker-compose

- name: Add the user to docker group
  user: name={{ user.name }} groups=docker append=yes

- name: Enable and start docker socket
  service: name=docker.socket enabled=yes state=started

- name: Install buildah
  pacman: name=buildah state=present

- name: Install podman
  pacman: name=podman state=present

- name: Install skopeo
  pacman: name=skopeo state=present
