---
- name: Install Virtualbox
  pacman:
    state: present
    name:
      - net-tools
      - virtualbox-guest-iso
      - virtualbox-guest-utils
      - virtualbox

- name: Install VirtualBox extensions
  aur: name=virtualbox-ext-oracle user={{ user.name }} dir=/tmp
  tags:
    - aur

- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes
